### ISSUE TITLE
linux/arm64 build

### ISSUE THREAD

**Issue by wilcosec** [Booyaabes/kali-linux-full-container#7]
With Apple Silicon processors becoming more commonly used, it would be great if this docker image could be built with arm64 support. 

I see you're already using `buildx`, which makes me think it shouldn't be too hard to add in a build for `linux/arm64`. 

Unfortunately I don't have any experience with GitHub Actions or even multi-arch Docker builds, so this is just a wishlist request from me. 

A few tutorials, in case they're useful:

1. https://dev.to/cloudx/multi-arch-docker-images-the-easy-way-with-github-actions-4k54/

2. https://blog.oddbit.com/post/2020-09-25-building-multi-architecture-im/

3. https://itnext.io/building-multi-cpu-architecture-docker-images-for-arm-and-x86-3-building-in-github-action-ci-a382feab5af9

**Comment by Booyaabes** [comment]
I’ve added armv7 and arm64 build. As I don’t have a Appel Silicon processor, I can’t make any test.
I’m closing this issue, please re-open it, if needed.
